image: node:18.12.0-bullseye

stages:
  - build
  - deploy
  - release

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn install
    - yarn lint
    - yarn build

deploy-qa-5:
  stage: deploy
  script:
    - yarn install
    - ./deploy-qa-5.sh

release:
  stage: release
  only:
    - tags
  script:
    - bash ./build-release.sh
    - apt update
    - apt install -y zip openjdk-17-jdk-headless
    - zip -r upay-bot-react-next.jar target
    - './mvnw
      --settings maven-release-settings.xml
      deploy:deploy-file
      -Durl=https://repo.clubber.me/nexus/content/repositories/paynet-release
      -DrepositoryId=paynet-release
      -Dfile=upay-bot-react-next.jar
      -DgroupId=com.payneteasy.upay-bot
      -DartifactId=upay-bot-react-next
      -Dversion=${CI_COMMIT_REF_NAME}
      -Dpackaging=jar
      -DgeneratePom=true'
